features:
  homes: true
  graves: true
  holograms: true
  damage-holograms: true
  double-doors: true
  chest-sort: true
  quick-stack: true
  pets: true
  recipes: true

homes:
  max: 5

quick-stack:
  radius: 5

pets:
  auto-attack-radius: 12
  hologram-radius: 32
  heal-on-kill: 4.0

items:
  max-rename-length: 64
  max-lore-line-length: 128